<Project Sdk="Microsoft.NET.Sdk">
  <!-- The command line. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Dexforge.Cli</AssemblyName>
    <RootNamespace>Dexforge.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dexforge.Core/Dexforge.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Dexforge.Cli.Tests" />
  </ItemGroup>
</Project>
